name: Build

env:
  EM_VERSION: 1.39.18
  EM_CACHE_FOLDER: "emsdk-cache"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Game
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}

      - name: Setup emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev \
            libusb-1.0-0-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev \
            libxss-dev libxtst-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev \
            libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev

      - name: Linux Build
        run: |
          mkdir build
          cmake -S . -B ./build -DSDL_UNIX_CONSOLE_BUILD=ON
          make -C build -j2

      - name: Web Build
        run: |
          mkdir web-build
          emcmake cmake -S . -B ./web-build -DSDL_UNIX_CONSOLE_BUILD=ON
          make -C web-build -j2

      - name: Upload Linux Build
        uses: actions/upload-artifact@v6
        with:
          name: linux-build
          path: build/snivy

      - name: Upload Web Build
        uses: actions/upload-artifact@v6
        with:
          name: web-build
          path: |
            .github/index.html
            web-build/index.*
